// このファイルは tools/import.js が data/*.csv から生成する。直接編集しない (次の import で上書きされる)。
export default [
  {
    "id": 1,
    "key": "poison",
    "kind": "common",
    "polarity": "bad",
    "side": "both",
    "duration": "stack",
    "characterId": -1,
    "name": "どく",
    "description": "行動の直前にスタック値のダメージ。ブロック・シールド貫通。回復で全部消える。",
    "icon": "poison",
    "sdLayer": "status_poison",
    "effect": "",
    "values": [],
    "next": "",
    "order": 1
  },
  {
    "id": 2,
    "key": "sleep",
    "kind": "common",
    "polarity": "bad",
    "side": "player",
    "duration": "turn",
    "characterId": -1,
    "name": "ねむり",
    "description": "手番をスキップ。敵の攻撃を受けると起きる。",
    "icon": "sleep",
    "sdLayer": "status_sleep",
    "effect": "",
    "values": [],
    "next": "",
    "order": 2
  },
  {
    "id": 3,
    "key": "paralyze",
    "kind": "common",
    "polarity": "bad",
    "side": "player",
    "duration": "stack",
    "characterId": -1,
    "name": "しびれ",
    "description": "武器を ON にできない。",
    "icon": "paralyze",
    "sdLayer": "status_paralyze",
    "effect": "",
    "values": [],
    "next": "",
    "order": 3
  },
  {
    "id": 4,
    "key": "arousal",
    "kind": "common",
    "polarity": "bad",
    "side": "player",
    "duration": "stack",
    "characterId": -1,
    "name": "はつじょう",
    "description": "アビリティを使えない。",
    "icon": "heart",
    "sdLayer": "status_arousal",
    "effect": "",
    "values": [],
    "next": "",
    "order": 4
  },
  {
    "id": 5,
    "key": "sticky",
    "kind": "common",
    "polarity": "bad",
    "side": "player",
    "duration": "stack",
    "characterId": -1,
    "name": "ねばねば",
    "description": "いつも後攻。",
    "icon": "nebaneba",
    "sdLayer": "status_sticky",
    "effect": "",
    "values": [],
    "next": "",
    "order": 5
  },
  {
    "id": 6,
    "key": "confusion",
    "kind": "common",
    "polarity": "bad",
    "side": "player",
    "duration": "stack",
    "characterId": -1,
    "name": "こんらん",
    "description": "インベントリがシャッフルされ、中身が見えない。",
    "icon": "confusion",
    "sdLayer": "status_confusion",
    "effect": "",
    "values": [],
    "next": "",
    "order": 6
  },
  {
    "id": 7,
    "key": "power",
    "kind": "common",
    "polarity": "good",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "こうげきアップ",
    "description": "この章のあいだ こうげき +n。",
    "icon": "adrenaline",
    "sdLayer": "",
    "effect": "",
    "values": [],
    "next": "",
    "order": 7
  },
  {
    "id": 8,
    "key": "abilityDamage",
    "kind": "common",
    "polarity": "good",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "アビリティアップ",
    "description": "この章のあいだ アビリティダメージ +n。",
    "icon": "comet",
    "sdLayer": "",
    "effect": "",
    "values": [],
    "next": "",
    "order": 8
  },
  {
    "id": 9,
    "key": "evade",
    "kind": "common",
    "polarity": "good",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "かいひ",
    "description": "敵の次の通常攻撃を 1 回だけ無効化 (1 ターンに 2 回攻撃されたら 2 回目は当たる)。",
    "icon": "feather",
    "sdLayer": "",
    "effect": "",
    "values": [],
    "next": "",
    "order": 9
  },
  {
    "id": 10,
    "key": "focus",
    "kind": "common",
    "polarity": "good",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "こうちょう",
    "description": "次の 1 回の通常攻撃のダメージ +2。",
    "icon": "adrenaline",
    "sdLayer": "",
    "effect": "",
    "values": [
      2
    ],
    "next": "",
    "order": 10
  },
  {
    "id": 11,
    "key": "ds_crystal",
    "kind": "unique",
    "polarity": "bad",
    "side": "player",
    "duration": "turn",
    "characterId": 1,
    "name": "けっしょうか",
    "description": "足が結晶に包まれて、バトルから逃げられない。",
    "icon": "crystal",
    "sdLayer": "unique_ds_crystal",
    "effect": "",
    "values": [],
    "next": "",
    "order": 11
  },
  {
    "id": 12,
    "key": "ds_fever",
    "kind": "unique",
    "polarity": "bad",
    "side": "player",
    "duration": "turn",
    "characterId": 1,
    "name": "たいおんじょうしょう",
    "description": "服を脱ぎ捨ててしまった。衣装は完全に破れ、なおすこともできない。",
    "icon": "fire",
    "sdLayer": "unique_ds_fever",
    "effect": "",
    "values": [],
    "next": "",
    "order": 12
  },
  {
    "id": 21,
    "key": "normal",
    "kind": "costume",
    "polarity": "neutral",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "ふつうの衣装",
    "description": "",
    "icon": "",
    "sdLayer": "costume_normal",
    "effect": "",
    "values": [],
    "next": "half",
    "order": 21
  },
  {
    "id": 22,
    "key": "half",
    "kind": "costume",
    "polarity": "neutral",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "衣装半破壊",
    "description": "こうげき -1。",
    "icon": "",
    "sdLayer": "costume_half",
    "effect": "",
    "values": [],
    "next": "full",
    "order": 22
  },
  {
    "id": 23,
    "key": "full",
    "kind": "costume",
    "polarity": "neutral",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "衣装破壊",
    "description": "こうげき -1、被ダメ +1。",
    "icon": "",
    "sdLayer": "costume_full",
    "effect": "",
    "values": [],
    "next": "full",
    "order": 23
  },
  {
    "id": 24,
    "key": "special1",
    "kind": "costume",
    "polarity": "neutral",
    "side": "player",
    "duration": "permanent",
    "characterId": -1,
    "name": "みずぎ",
    "description": "1 ターン目、相手の攻撃力 -4。クロスブレイクで元にもどる。",
    "icon": "",
    "sdLayer": "costume_special1",
    "effect": "",
    "values": [
      4
    ],
    "next": "normal",
    "order": 24
  },
  {
    "id": 31,
    "key": "powerDelta",
    "kind": "buff",
    "polarity": "neutral",
    "side": "both",
    "duration": "stack",
    "characterId": -1,
    "name": "こうげき変化",
    "description": "このバトル中の攻撃力の変化。",
    "icon": "",
    "sdLayer": "",
    "effect": "",
    "values": [],
    "next": "",
    "order": 31
  },
  {
    "id": 32,
    "key": "blockDelta",
    "kind": "buff",
    "polarity": "neutral",
    "side": "both",
    "duration": "stack",
    "characterId": -1,
    "name": "ブロック変化",
    "description": "このバトル中のブロックの変化。",
    "icon": "",
    "sdLayer": "",
    "effect": "",
    "values": [],
    "next": "",
    "order": 32
  }
];
