// ============================================================
// サウンドマスタ — 「ファイル一覧がマスタ」方式 (09)。ここに並べたものがロードされ、キーで再生できる。
// file は public/assets/sounds/ からの相対パス。BGM のループ点はコード側 (sampleRate / loopStartSamples / loopLengthSamples)。
// 音源は tale が使っていた xqueens の音を仮に流用 (tools/placeholders.js)
// ============================================================
export default {
  se: {
    hover: { file: "se/hover.ogg", volume: 1 },
    select: { file: "se/select.ogg", volume: 1 },
    ok: { file: "se/ok.ogg", volume: 1 },
    ok2: { file: "se/ok2.ogg", volume: 1 },
    ng: { file: "se/ng.ogg", volume: 1 },
    cancel: { file: "se/cancel.ogg", volume: 1 },
    close: { file: "se/close.ogg", volume: 1 },
    open: { file: "se/open.ogg", volume: 1 },
    equip: { file: "se/equip.ogg", volume: 1 },
    unequip: { file: "se/unequip.ogg", volume: 1 },
    buy: { file: "se/buy.ogg", volume: 1 },
    damage: { file: "se/damage.ogg", volume: 1 },
    receiveDamage: { file: "se/receiveDamage.ogg", volume: 1 },
    guard: { file: "se/guard.ogg", volume: 1 },
    break: { file: "se/break.ogg", volume: 1 },
    critical: { file: "se/critical.ogg", volume: 1 },
    combo: { file: "se/combo.ogg", volume: 1 },
    draw: { file: "se/draw.ogg", volume: 1 },
    gameStart: { file: "se/gameStart.ogg", volume: 1 },
    win: { file: "se/win.ogg", volume: 1 },
    lose: { file: "se/lose.ogg", volume: 1 },
    turnStart: { file: "se/turnStart.ogg", volume: 1 },
    turnEnd: { file: "se/turnEnd.ogg", volume: 1 },
    tips: { file: "se/tips.ogg", volume: 1 },
    skill: { file: "se/skill.ogg", volume: 1 },
    achievement: { file: "se/achievement.ogg", volume: 1 },
    menu: { file: "se/menu.ogg", volume: 1 },
    option: { file: "se/option.ogg", volume: 1 },
    purify: { file: "se/purify.ogg", volume: 1 },
    pokerChip: { file: "se/pokerChip.ogg", volume: 1 },
    charm: { file: "se/charm.ogg", volume: 1 },
  },
  bgm: {
    title: { file: "bgm/title.ogg", volume: 1, loop: true },
    chara1: { file: "bgm/chara11.ogg", volume: 1, loop: true, sampleRate: 48000, loopStartSamples: 0, loopLengthSamples: 4704000 },
    chara0: { file: "bgm/chara12.ogg", volume: 1, loop: true, sampleRate: 48000, loopStartSamples: 751304, loopLengthSamples: 5426087 },
    shop: { file: "bgm/shop.ogg", volume: 1, loop: true, sampleRate: 44100, loopStartSamples: 2125263, loopLengthSamples: 2945131 },
    result: { file: "bgm/result.ogg", volume: 1, loop: true, sampleRate: 48000, loopStartSamples: 2431408, loopLengthSamples: 4438448 },
  },
};

// outbox の一発物 → SE (app 側の表。core は音を知らない)
export const EVENT_SE = {
  panelTake: "draw",
  panelDump: "cancel",
  panelFall: "select",
  bossAppear: "achievement",
  battleStart: "gameStart",
  playerStrike: "damage",
  enemyAttack: "receiveDamage",
  enemyBlocked: "guard",
  parry: "critical",
  equipToggle: "equip",
  itemUse: "skill",
  abilityUse: "skill",
  abilityReady: "purify",
  heal: "purify",
  statusApply: "charm",
  crossBreak: "break",
  equipBreak: "break",
  itemBreak: "break",
  victory: "win",
  defeat: "lose",
  rewards: "pokerChip",
  relicGain: "buy",
  panelBuy: "buy",
  shopReroll: "draw",
  chapterClearAppear: "achievement",
  chapterClearTake: "achievement",
  eventChoose: "ok2",
  battleCancel: "cancel",
  lethalScythe: "critical",
  justLethal: "combo",
  enemyAttackNegated: "guard",
  enemyShieldAbsorb: "guard",
  uniqueApply: "charm",
  coinGain: "pokerChip",
  loseEntities: "break",
  harshnessGain: "charm",
  pendingGain: "ng",
  bookRuleProc: "purify",
  gain: "equip",
};
